name: Build and Push Docker image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean install

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: target/app.jar
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/game-app:1.0.0

    - name: Run the image
      run: docker run ${{ secrets.DOCKER_USERNAME }}/game-app:1.0.0
