name: Build and Push Docker image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean install

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: target/game-app-0.0.1-SNAPSHOT.jar
        
    - name: List output files
      run: ls -l target/ 

    - name: Extract version from Dockerfile
      id: extract_version
      run: |
        VERSION=$(grep 'LABEL version=' Dockerfile | cut -d '"' -f2)
        echo "Extracted Version: $VERSION"
        echo "::set-output name=version::$VERSION"
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  # Dies sollte auf das Wurzelverzeichnis des Repos zeigen
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/game-app:${{ steps.extract_version.outputs.version }}


